image:
  pullPolicy: IfNotPresent

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: mkcert
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
        # external-dns annotation removed (not using ExternalDNS)
    hosts:
      - host: nzbget.homelab.local
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: nzbget.homelab.local
      hosts:
      - nzbget.homelab.local

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 5Gi
    mountPath: /config

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0