image:
  pullPolicy: IfNotPresent

env:
  TZ: America/Toronto
  PGID: 0
  PUID: 0

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: mkcert
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  # external-dns annotations removed (not using ExternalDNS)
    hosts:
      - host: ombi.homelab.local
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: ombi.homelab.local
      hosts:
      - ombi.homelab.local

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 5Gi